### ISSUE TITLE
how to get "vertified_books" ?

### ISSUE THREAD

**Issue by Guozhongyuan** [Spritualkb/yuque-spider-plus#1]
Hello, how can I get "vertified_books" on browser?
`python main.py https://www.yuque.com/xxx/xxx "vertified_books=******"`

**Comment by Spritualkb** [comment]
Open the F12 capture packet and enter the password to retrieve the cookie from the following request packet and find vertified_books from inside

**Comment by Spritualkb** [comment]
I can see why you can't find it. You have to type in that url without logging in. You can go to that URL with a different browser, so you can catch vertified_books

**Comment by Spritualkb** [comment]
Of course, you can also paste all the cookies on it, which is fine
